spring:
  profiles:
    default: local  # 기본적으로 활성화할 프로파일을 local 로 설정

---
spring:
  config:
    activate:
      import: optional:file:.env[.properties]
      on-profile: local
  # 로컬 환경 설정
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
openapi:
  key: ${OPEN_API_KEY}
kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: ${REDIRECT_URL}
  local_redirect_uri: ${LOCAL_REDIRECT_URL}
naver:
  naver_redirect_url: ${NAVER_REDIRECT_URL}
  naver_client_id: ${NAVER_CLIENT_ID}
  naver_client_secret: ${NAVER_CLIENT_SECRET}
  naver_local_redirect_uri: ${NAVER_LOCAL_REDIRECT}
fcm:
  file_path: "resources/fcm/youthstepup-29a94-firebase-adminsdk-rx9v3-c8488edfc9.json"
  url: https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: ${PROJECT_ID}

Jwt:
  secret: ${JWT_SECRET_KEY}
  token:
    access-expiration-time: 1800000 #30분 60
    refresh-expiration-time: 259200000 #1일

---
spring:
  config:
    activate:
      on-profile: prod
  # 프로덕션 환경 설정
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
Jwt:
  secret: ${JWT_SECRET_KEY}
  token:
    access-expiration-time: 1800000 #30분 60
    refresh-expiration-time: 259200000

openapi:
  key: ${OPEN_API_KEY}

kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: ${REDIRECT_URL}
  local_redirect_uri: ${LOCAL_REDIRECT_URL}
naver:
  naver_redirect_url: ${NAVER_REDIRECT_URL}
  naver_client_id: ${NAVER_CLIENT_ID}
  naver_client_secret: ${NAVER_CLIENT_SECRET}
  naver_local_redirect_uri: ${NAVER_LOCAL_REDIRECT}
fcm:
  file_path: ${FCM_FILE_PATH}
  url: https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: ${PROJECT_ID}

logging:
  level:
    root: debug